set_property PACKAGE_PIN W4 [get_ports {Display[3]}]
set_property PACKAGE_PIN V4 [get_ports {Display[2]}]
set_property PACKAGE_PIN U4 [get_ports {Display[1]}]
set_property PACKAGE_PIN U2 [get_ports {Display[0]}]
set_property PACKAGE_PIN W7 [get_ports {led[6]}]
set_property PACKAGE_PIN W6 [get_ports {led[5]}]
set_property PACKAGE_PIN U8 [get_ports {led[4]}]
set_property PACKAGE_PIN V8 [get_ports {led[3]}]
set_property PACKAGE_PIN U5 [get_ports {led[2]}]
set_property PACKAGE_PIN V5 [get_ports {led[1]}]
set_property PACKAGE_PIN U7 [get_ports {led[0]}]

set_property PACKAGE_PIN N17 [get_ports {sensores[2]}]
set_property PACKAGE_PIN M18 [get_ports {sensores[1]}]
set_property PACKAGE_PIN K17 [get_ports {sensores[0]}]

set_property PACKAGE_PIN R2 [get_ports reset]
set_property PACKAGE_PIN W5 [get_ports timer]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {sensores[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sensores[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sensores[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports timer]