#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Aug 30 12:06:43 CST 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 163e3bef2042464e9c5cf111b231e722 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot codigo_behav xil_defaultlib.codigo -log elaborate.log"
xelab -wto 163e3bef2042464e9c5cf111b231e722 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot codigo_behav xil_defaultlib.codigo -log elaborate.log

