set_property SRC_FILE_INFO {cfile:{/home/axel/Documentos/Proyectos de Arqui 2/Vivado/Lab 2/Lab 2 - Encender led/Lab 2 - Encender led.srcs/constrs_1/new/cst_led.xdc} rfile:{../../../Lab 2 - Encender led.srcs/constrs_1/new/cst_led.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports modulador[0]]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports modulador[1]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports modulador[2]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports led]
